EMAIL_SENDER = "yosps95@gmail.com"
EMAIL_PASSWORD = "hdxd rrfa qocr efbx"
EMAIL_RECEIVER = "yosps95@gmail.com"
TELEGRAM_TOKEN = "7711945483:AAFPoHUFknDesF1z10EdYJ_UL94vxLb9aT4"
TELEGRAM_CHAT_ID = "6084218415"
